name: 'test'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  vim:
    env:
      - EXRC_VIM: 'vim'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'rhysd/action-setup-vim@v1'
      - name: 'test'
        run: ./tests/run.sh

  nvim:
    env:
      - EXRC_VIM: 'nvim'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'rhysd/action-setup-vim@v1'
        with:
          neovim: true
      - name: 'test'
        run: ./tests/run.sh
