name: 'test'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'setup'
        run: >
          sudo apt-get update -y \
            && sudo apt-get upgrade -y \
            && sudo apt-get install -y vim \

      - name: 'test'
        run: ./tests/run.sh
